# TUGAS UTS PENAMBANGAN DATA :  K-Nearest Neighbors and Naive Bayes Classification Method on Heart Disease Prediction

NAMA : MOHAMMAD IQBAL SURYA RAMADHAN

NIM : 210411100002

KELAS : PENAMBANGAN DATA C

**Naive Bayes**

*Naive Bayes merupakan sebuah metode klasifikasi menggunakan metode probabilitas dan statistik yg dikemukakan oleh ilmuwan Inggris Thomas Bayes. Ciri utama dr Naïve Bayes Classifier ini adalah asumsi yg sangat kuat (naïf) akan independensi dari masing-masing kondisi / kejadian. Keuntungan dari pendekatan ini yaitu pengklasifikasian akan mendapatkan nilai error yang lebih kecil ketika data set berjumlah besar.*

**K-Nearest Neighbors**

*K-nearest neighbors atau knn adalah algoritma yang berfungsi untuk melakukan klasifikasi suatu data berdasarkan data pembelajaran (train data sets), yang diambil dari k tetangga terdekatnya (nearest neighbors). Dengan k merupakan banyaknya tetangga terdekat.*

**Untuk melakukan klasifikasi terlebih dahulu mengaktifkan package yang dibutuhkan untuk melakukan analisis dengan Python yaitu Pandas dan Numpy**

In [247]:
import pandas as pd
import numpy as np

**Data input**

*Selanjutnya masukkan data Prediksi Penyakit Jantung dengan fungsi*

‘pd.read_csv()’ dan tampilkan 5 data teratas dengan fungsi ‘.head()’ 

*seperti berikut :*

In [248]:
dataset = pd.read_csv('https://raw.githubusercontent.com/Iqbalsuryaa/pendata/main/HeartDiseasePrediction.csv')
dataset.head(10)

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   
5   57    1   0       140   192    0        1      148      0      0.4      1   
6   56    0   1       140   294    0        0      153      0      1.3      1   
7   44    1   1       120   263    0        1      173      0      0.0      2   
8   52    1   2       172   199    1        1      162      0      0.5      2   
9   57    1   2       150   168    0        1      174      0      1.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1  
5   0     1       1  
6   0     2       1  
7   0     3       1  
8   0     3       1  
9   0     2       1

**Data Information**

*Untuk menampilkan informasi data yang telah dimasukkan digunakan*

In [249]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


**Variable Selection**

*Pada tahapan ini, akan dilakukan pemilihan variabel baik untuk variabel independen maupun variabel dependen.*

*Variabel independen diberi nama x. Untuk mempermudah maka keluarkan variabel Donated dari data tersebut dengan fungsi ‘.drop’. Axis =1 yang berarti bahwa semua variabel kecuali **variabel target** merupakan variabel independen*

In [250]:
x = dataset.drop(["target"], axis = 1)
x.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  
0   0     1  
1   0     2  
2   0     2  
3   0     2  
4   0     2

**pilih variabel dependen yang diberi nama y. Variabel dependen pada kasus ini adalah Donated.**

In [251]:
y = dataset["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

**Spliting Data Train dan Data Test**

*Untuk melakukan pembagian data train dan test, pertama perlu mengimport fungsi untuk membagi data dari library scikit-learn. Scikit-Learn memberikan sejumlah fitur untuk keperluan data science.*

*Data Blood Transfusion akan dibagi menjadi 2 bagian yaitu x test dan x train untuk variabel independen, y test dan y train untuk variabel dependen.*

In [252]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

**Scaling Data**

*Menyamakan skala data dengan menggunakan fungsi ‘StandarScaler’ dari package scikit-learn. Teknik Standard Scaler berguna ketika membandingkan data yang sesuai dengan unit yang berbeda. Standard Scaler mengubah data yang sedemikian rupa sehingga distribusinya memiliki nilai rata-rata 0 dan standar deviasi 1.*



In [253]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()  
scaler.fit(x_train)

x_train = scaler.transform(x_train)  
x_test = scaler.transform(x_test)

**Klasifikasi dengan KNN**

*Klasifikasi pertama akan menggunakan KNN, dengan mengimport fungsi KNeighborsClassifier dari package scikit-learn.*

In [254]:
from sklearn.neighbors import KNeighborsClassifier

**Mengaktifkan atau memanggil fungsi klasifikasi KNN**

In [255]:
knn = KNeighborsClassifier(n_neighbors=8)

**Memasukkan data training pada fungsi klasifikasi KNN**

In [256]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=8)

**Menentukan hasil prediksi dari x_test yang disebut dengan y prediksi**

In [257]:
y_pred = knn.predict(x_test)
y_pred

array([1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0])

**Menentukan probabilitas hasil prediksi**

In [258]:
knn.predict_proba(x_test)

array([[0.   , 1.   ],
       [0.875, 0.125],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [0.   , 1.   ],
       [1.   , 0.   ],
       [0.125, 0.875],
       [0.625, 0.375],
       [0.25 , 0.75 ],
       [0.25 , 0.75 ],
       [0.875, 0.125],
       [0.625, 0.375],
       [1.   , 0.   ],
       [1.   , 0.   ],
       [0.625, 0.375],
       [1.   , 0.   ],
       [0.625, 0.375],
       [0.625, 0.375],
       [0.625, 0.375],
       [0.125, 0.875],
       [0.25 , 0.75 ],
       [0.5  , 0.5  ],
       [0.   , 1.   ],
       [0.75 , 0.25 ],
       [0.5  , 0.5  ],
       [0.5  , 0.5  ],
       [0.875, 0.125],
       [0.375, 0.625],
       [1.   , 0.   ],
       [0.5  , 0.5  ],
       [1.   , 0.   ],
       [0.375, 0.625],
       [0.   , 1.   ],
       [0.75 , 0.25 ],
       [0.375, 0.625],
       [0.   , 1.   ],
       [0.125, 0.875],
       [0.375, 0.625],
       [0.   , 1.   ],
       [0.125, 0.875],
       [0.125, 0.875],
       [0.375, 0.625],
       [0.875, 0.125],
       [0. 

**Import fungsi confusion matrix dari package scikit-learn**

In [259]:
from sklearn.metrics import classification_report, confusion_matrix

**Confusion matrix adalah suatu metode yang biasanya digunakan untuk melakukan perhitungan akurasi. Confusion matrix akan menampilkan perbandingan nilai akurasi dari y test dengan y prediksi.**

**Menampilkan confusion matrix dari hasil prediksi dengan metode KNN**

In [260]:
print(confusion_matrix(y_test, y_pred))

[[25  5]
 [ 7 24]]


**Menampilkan laporan klasifikasi yang berisi beberapa nilai dengan menggunakan fungsi ‘classification_report’ yang diimport dari package scikit-learn.**

In [261]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.78      0.83      0.81        30
           1       0.83      0.77      0.80        31

    accuracy                           0.80        61
   macro avg       0.80      0.80      0.80        61
weighted avg       0.80      0.80      0.80        61



**Mengetahui nilai akurasi dengan model yang ada maka lakukan perhitungan berikut : (True Positive / True Negative )/ n berdasarkan nilai yang ada pada confusion matrix**

In [262]:
#accuracy = tp+tn/total
accuracy = (25+24)/61
accuracy

0.8032786885245902

**Klasifikasi dengan Metode Naive Bayes**



*Klasifikasi selanjutnya menggunakan metode Naive Bayes dengan mengimport fungsi GaussianNB dari package scikit-learn.*

In [263]:
from sklearn.naive_bayes import GaussianNB

** Mengaktifkan atau memanggil fungsi klasifikasi Naive Bayes**

In [264]:
modelnb = GaussianNB()

**Memasukkan data training pada fungsi klasifikasi Naive Bayes**

In [265]:
nbtrain = modelnb.fit(x_train, y_train)

**Selanjutnya menghitung jumlah pada class-class dari model nbtrain**

In [266]:
nbtrain.class_count_

array([108., 134.])

**Menentukan hasil prediksi dari x_test yang disebut dengan y prediksi**

In [267]:
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0])

**Menentukan probabilitas hasil prediksi**

In [268]:
nbtrain.predict_proba(x_test)

array([[5.82519301e-04, 9.99417481e-01],
       [9.99240660e-01, 7.59340083e-04],
       [9.99938876e-01, 6.11239119e-05],
       [9.99992659e-01, 7.34091227e-06],
       [3.63340453e-03, 9.96366595e-01],
       [9.99951075e-01, 4.89245485e-05],
       [8.58705904e-03, 9.91412941e-01],
       [5.98824205e-01, 4.01175795e-01],
       [5.96179179e-04, 9.99403821e-01],
       [9.33512783e-01, 6.64872171e-02],
       [9.97942511e-01, 2.05748946e-03],
       [4.57119010e-01, 5.42880990e-01],
       [9.99999986e-01, 1.36201854e-08],
       [9.99995731e-01, 4.26929475e-06],
       [5.16997591e-01, 4.83002409e-01],
       [1.00000000e+00, 5.08299544e-11],
       [9.10170340e-01, 8.98296597e-02],
       [9.86810593e-01, 1.31894074e-02],
       [5.72080552e-01, 4.27919448e-01],
       [2.24337668e-01, 7.75662332e-01],
       [1.35284858e-01, 8.64715142e-01],
       [9.99163391e-01, 8.36609347e-04],
       [4.11790193e-05, 9.99958821e-01],
       [9.82142823e-01, 1.78571775e-02],
       [9.874890

**Import fungsi confusion matrix dari package scikit-learn**

In [269]:
from sklearn.metrics import classification_report, confusion_matrix

**Menampilkan confusion matrix dari hasil prediksi dengan metode Naive Bayes**

In [270]:
confusion_matrix(y_test, y_pred)

array([[27,  3],
       [ 7, 24]])

**Menampilkan laporan klasifikasi yang berisi beberapa nilai dengan menggunakan fungsi ‘classification_report’ yang diimport dari package scikit-learn.**

In [271]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.79      0.90      0.84        30
           1       0.89      0.77      0.83        31

    accuracy                           0.84        61
   macro avg       0.84      0.84      0.84        61
weighted avg       0.84      0.84      0.84        61



**Mengetahui nilai akurasi dengan model yang ada maka lakukan perhitungan berikut : (True Positive / True Negative )/ n berdasarkan nilai yang ada pada confusion matrix**

In [272]:
#accuracy = tp+tn/total
accuracy = (27+24)/61
accuracy

0.8360655737704918