NAMA : MOHAMMAD IQBAL SURYA RAMADHAN

NIM  : 210411100002

Mata Kuliah Penambangan Data - C

**Penjelasan Tipe Data :**

## **>> Pengujian Naive Bayes Tanpa PCA**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import StandardScaler

In [ ]:
HumanStress = pd.read_csv('https://raw.githubusercontent.com/Iqbalsuryaa/pendata/main/SaYoPillow.csv')
HumanStress

sr      rr       t      lm      bo     rem   sr.1     hr  sl
0    93.800  25.680  91.840  16.600  89.840   99.60  1.840  74.20   3
1    91.640  25.104  91.552  15.880  89.552   98.88  1.552  72.76   3
2    60.000  20.000  96.000  10.000  95.000   85.00  7.000  60.00   1
3    85.760  23.536  90.768  13.920  88.768   96.92  0.768  68.84   3
4    48.120  17.248  97.872   6.496  96.248   72.48  8.248  53.12   0
..      ...     ...     ...     ...     ...     ...    ...    ...  ..
625  69.600  20.960  92.960  10.960  90.960   89.80  3.440  62.40   2
626  48.440  17.376  98.064   6.752  96.376   73.76  8.376  53.44   0
627  97.504  27.504  86.880  17.752  84.256  101.88  0.000  78.76   4
628  58.640  19.728  95.728   9.728  94.592   84.32  6.728  59.32   1
629  73.920  21.392  93.392  11.392  91.392   91.96  4.088  63.48   2

[630 rows x 9 columns]

In [ ]:
HumanStress =HumanStress
X = HumanStress.iloc[:,:6].values
y = HumanStress['sl'].values
HumanStress.head(5)

sr      rr       t      lm      bo    rem   sr.1     hr  sl
0  93.80  25.680  91.840  16.600  89.840  99.60  1.840  74.20   3
1  91.64  25.104  91.552  15.880  89.552  98.88  1.552  72.76   3
2  60.00  20.000  96.000  10.000  95.000  85.00  7.000  60.00   1
3  85.76  23.536  90.768  13.920  88.768  96.92  0.768  68.84   3
4  48.12  17.248  97.872   6.496  96.248  72.48  8.248  53.12   0

In [ ]:
from sklearn.preprocessing import StandardScaler
X_std=StandardScaler().fit_transform(X)
X_std

array([[ 1.14684518,  0.97906569, -0.2721947 ,  1.14053872, -0.27183777,
         0.9340051 ],
       [ 1.03526024,  0.83371986, -0.35385311,  0.97294936, -0.34569558,
         0.87342099],
       [-0.59925243, -0.45420573,  0.90731566, -0.39569711,  1.05144797,
        -0.29450611],
       ...,
       [ 1.33819268,  1.43932751, -1.67853398,  1.4086817 , -1.70385862,
         1.1258548 ],
       [-0.66950962, -0.52284127,  0.83019383, -0.45900864,  0.94681608,
        -0.35172444],
       [ 0.11985049, -0.1029533 ,  0.1678534 , -0.07169101,  0.12617376,
         0.29114033]])

In [ ]:
df_std = pd.DataFrame(X_std, columns=HumanStress.columns[:6])
df_std.to_csv('preprocessed_data.csv', index=False)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.05, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 3, 2, 0, 3, 2, 3, 1, 0, 0, 2, 4, 2, 2, 1, 4, 1, 4, 1, 2, 0, 0,
       4, 0, 0, 2, 4, 0, 2, 2, 2, 0])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))
cm

Accuracy :  1.0


array([[10,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0, 10,  0,  0],
       [ 0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  5]])

In [ ]:
# Mendefinisikan fungsi untuk memprediksi RiskLevel dari input pengguna
def predict_risk_level(input_data):
    # Lakukan preprocessing pada input data
    input_data = sc.transform([input_data])  # Lakukan penskalaan pada input data

    # Lakukan prediksi menggunakan model Gaussian Naive Bayes
    predicted_risk_level = classifier.predict(input_data)

    return predicted_risk_level

In [ ]:
# Contoh penggunaan fungsi predict_risk_level dengan input pengguna
input_user = [15,120,80,7.01,98,70]
predicted_risk = predict_risk_level(input_user)
print("Predicted Risk Level:", predicted_risk)

Predicted Risk Level: [3]


## **>> Pengujian K - Nearest Neighbour Tanpa PCA**

In [ ]:
import pandas as pd
import sklearn

In [ ]:
dataset = pd.read_csv('https://raw.githubusercontent.com/Iqbalsuryaa/pendata/main/SaYoPillow.csv')
dataset.head(10)

sr      rr       t      lm      bo    rem   sr.1     hr  sl
0  93.80  25.680  91.840  16.600  89.840  99.60  1.840  74.20   3
1  91.64  25.104  91.552  15.880  89.552  98.88  1.552  72.76   3
2  60.00  20.000  96.000  10.000  95.000  85.00  7.000  60.00   1
3  85.76  23.536  90.768  13.920  88.768  96.92  0.768  68.84   3
4  48.12  17.248  97.872   6.496  96.248  72.48  8.248  53.12   0
5  56.88  19.376  95.376   9.376  94.064  83.44  6.376  58.44   1
6  47.00  16.800  97.200   5.600  95.800  68.00  7.800  52.00   0
7  50.00  18.000  99.000   8.000  97.000  80.00  9.000  55.00   0
8  45.28  16.112  96.168   4.224  95.112  61.12  7.112  50.28   0
9  55.52  19.104  95.104   9.104  93.656  82.76  6.104  57.76   1

In [ ]:
HumanStress = HumanStress
X = HumanStress.iloc[:,:6].values
y = HumanStress['sl'].values
HumanStress.head(5)

sr      rr       t      lm      bo    rem   sr.1     hr  sl
0  93.80  25.680  91.840  16.600  89.840  99.60  1.840  74.20   3
1  91.64  25.104  91.552  15.880  89.552  98.88  1.552  72.76   3
2  60.00  20.000  96.000  10.000  95.000  85.00  7.000  60.00   1
3  85.76  23.536  90.768  13.920  88.768  96.92  0.768  68.84   3
4  48.12  17.248  97.872   6.496  96.248  72.48  8.248  53.12   0

In [ ]:
from sklearn.preprocessing import StandardScaler
X_std=StandardScaler().fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [ ]:
y_pred = classifier.predict(X_test)
y_pred

array([0, 3, 2, 0, 3, 2, 3, 1, 0, 0, 2, 4, 2, 2, 1, 4, 1, 4, 1, 2, 0, 0,
       4, 0, 0, 2, 4, 0, 2, 2, 2, 0, 2, 2, 4, 0, 3, 2, 3, 3, 4, 4, 1, 0,
       4, 1, 1, 3, 3, 3, 1, 3, 2, 3, 0, 1, 0, 1, 3, 0, 3, 3, 0])

In [ ]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))
cm

Accuracy :  1.0


array([[16,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0],
       [ 0,  0, 14,  0,  0],
       [ 0,  0,  0, 14,  0],
       [ 0,  0,  0,  0,  9]])

## **>> Pengujian Decision Tree Tanpa PCA**

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/Iqbalsuryaa/pendata/main/SaYoPillow.csv')
df.head()

sr      rr       t      lm      bo    rem   sr.1     hr  sl
0  93.80  25.680  91.840  16.600  89.840  99.60  1.840  74.20   3
1  91.64  25.104  91.552  15.880  89.552  98.88  1.552  72.76   3
2  60.00  20.000  96.000  10.000  95.000  85.00  7.000  60.00   1
3  85.76  23.536  90.768  13.920  88.768  96.92  0.768  68.84   3
4  48.12  17.248  97.872   6.496  96.248  72.48  8.248  53.12   0

In [ ]:
X = df.drop(['sl'], axis=1)
y = df['sl']

In [ ]:
from sklearn.preprocessing import StandardScaler
X_std=StandardScaler().fit_transform(X)

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 42)

In [ ]:
!pip install category_encoders
import category_encoders as ce

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=21)
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=21)

In [ ]:
y_pred_gini = clf_gini.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score
print('Model accuracy score with criterion gini index: {0:0.2f}'. format(accuracy_score(y_test, y_pred_gini)))

Model accuracy score with criterion gini index: 0.97


In [ ]:
y_pred_train_gini = clf_gini.predict(X_train)
y_pred_train_gini

array([2, 0, 1, 4, 2, 3, 0, 2, 3, 1, 4, 3, 4, 3, 1, 2, 3, 3, 4, 3, 4, 1,
       4, 2, 2, 1, 3, 4, 1, 2, 4, 4, 2, 4, 4, 2, 4, 4, 0, 1, 2, 1, 1, 1,
       1, 3, 1, 2, 4, 1, 3, 0, 0, 1, 0, 4, 0, 2, 3, 2, 2, 4, 3, 0, 0, 1,
       2, 1, 0, 3, 0, 2, 0, 0, 0, 2, 1, 2, 4, 2, 0, 4, 0, 1, 1, 0, 1, 3,
       0, 4, 3, 3, 4, 3, 1, 3, 2, 0, 0, 2, 2, 4, 2, 4, 1, 2, 1, 0, 3, 4,
       2, 1, 0, 4, 2, 0, 3, 3, 1, 4, 4, 2, 3, 4, 1, 3, 1, 3, 2, 2, 0, 1,
       4, 3, 2, 1, 1, 3, 4, 3, 2, 4, 2, 4, 2, 1, 4, 3, 4, 4, 2, 2, 1, 4,
       3, 2, 1, 3, 2, 0, 1, 1, 2, 4, 4, 4, 4, 0, 0, 2, 0, 1, 0, 4, 4, 0,
       3, 3, 2, 0, 0, 3, 0, 1, 2, 2, 1, 1, 0, 1, 3, 3, 0, 2, 4, 4, 4, 4,
       4, 3, 3, 2, 2, 1, 4, 1, 1, 1, 1, 2, 0, 4, 1, 0, 4, 0, 3, 0, 1, 3,
       2, 0, 3, 3, 2, 3, 1, 1, 1, 4, 3, 3, 0, 1, 3, 0, 2, 2, 1, 4, 3, 2,
       4, 1, 1, 1, 0, 3, 2, 1, 2, 4, 2, 3, 4, 2, 1, 0, 0, 0, 4, 2, 4, 1,
       1, 4, 1, 4, 2, 2, 2, 0, 2, 3, 4, 1, 1, 0, 3, 0, 4, 1, 1, 2, 0, 1,
       4, 3, 0, 1, 4, 1, 4, 2, 0, 4, 4, 4, 4, 0, 0,

In [ ]:
print('Training-set accuracy score: {0:0.2f}'. format(accuracy_score(y_train, y_pred_train_gini)))

Training-set accuracy score: 1.00


In [ ]:
print('Training set score: {:.2f}'.format(clf_gini.score(X_train, y_train)))
print('Test set score: {:.2f}'.format(clf_gini.score(X_test, y_test)))

Training set score: 1.00
Test set score: 0.97


## **>> Pengujian Artificial Neural Network Tanpa PCA**


In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [ ]:
df=pd.read_csv('https://raw.githubusercontent.com/Iqbalsuryaa/pendata/main/SaYoPillow.csv')
df.head()

sr      rr       t      lm      bo    rem   sr.1     hr  sl
0  93.80  25.680  91.840  16.600  89.840  99.60  1.840  74.20   3
1  91.64  25.104  91.552  15.880  89.552  98.88  1.552  72.76   3
2  60.00  20.000  96.000  10.000  95.000  85.00  7.000  60.00   1
3  85.76  23.536  90.768  13.920  88.768  96.92  0.768  68.84   3
4  48.12  17.248  97.872   6.496  96.248  72.48  8.248  53.12   0

In [ ]:
from sklearn.preprocessing import StandardScaler
X_std=StandardScaler().fit_transform(X)

In [ ]:
X = df.drop(['sl'], axis=1)
y = df['sl']

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [ ]:
# Memisahkan fitur dan target
X = df.drop('sl', axis=1)
y = df['sl']

In [ ]:
# Standarisasi fitur
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

In [ ]:
# Memisahkan data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X_std, y, test_size=0.1, random_state=42)

In [ ]:
# Membuat objek MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(100,100,100), max_iter=1000, alpha=0.0001,
                     solver='sgd', verbose=10,  random_state=21,tol=0.001)

In [ ]:
# Melatih model dengan data latih
mlp.fit(X_train, y_train)

Iteration 1, loss = 1.59693172
Iteration 2, loss = 1.58443011
Iteration 3, loss = 1.56427525
Iteration 4, loss = 1.54138450
Iteration 5, loss = 1.51479483
Iteration 6, loss = 1.48736632
Iteration 7, loss = 1.46066070
Iteration 8, loss = 1.43377289
Iteration 9, loss = 1.40791666
Iteration 10, loss = 1.38204104
Iteration 11, loss = 1.35740256
Iteration 12, loss = 1.33307249
Iteration 13, loss = 1.31018578
Iteration 14, loss = 1.28729440
Iteration 15, loss = 1.26631176
Iteration 16, loss = 1.24617173
Iteration 17, loss = 1.22641396
Iteration 18, loss = 1.20797211
Iteration 19, loss = 1.18982196
Iteration 20, loss = 1.17253980
Iteration 21, loss = 1.15566562
Iteration 22, loss = 1.13926419
Iteration 23, loss = 1.12353490
Iteration 24, loss = 1.10804014
Iteration 25, loss = 1.09269082
Iteration 26, loss = 1.07776289
Iteration 27, loss = 1.06336916
Iteration 28, loss = 1.04906570
Iteration 29, loss = 1.03545481
Iteration 30, loss = 1.02190693
Iteration 31, loss = 1.00889268
Iteration 32, los

MLPClassifier(hidden_layer_sizes=(100, 100, 100), max_iter=1000,
              random_state=21, solver='sgd', tol=0.001, verbose=10)

In [ ]:
# Memprediksi kelas dari data uji
y_pred = mlp.predict(X_test)

In [ ]:
# Menghitung akurasi
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi:", accuracy)

Akurasi: 1.0
