# UAS PENAMBANGAN DATA


NAMA : MOHAMMAD IQBAL SURYA RAMADHAN

NIM  : 210411100002

Mata Kuliah Penambangan Data - C

**Penjelasan Tipe Data :**

Gender : wanita atau pria, yang Merupakan type data Kategorial yang nantinya akan kita ubah ke type data biner, dengan nilai value 1 untuk wanita dan value 0 untuk pria.

dahi_lebar_cm : lebar dahi dari kanan ke kiri diberikan dalam ukuran cm. Merupakan type data Numeric

dahi_tinggi_cm : lebar dahi lebar dalam ukuran cm dari tempat rambut tumbuh ke alis.
Merupakan type data Numeric.

Apakah memiliki hidung yang lebar atau tidak : 1 mewakili lebar dan 0 tidak.
Merupakan Type data biner.

Apakah memiliki hidung yang panjang atau tidak : 1 mewakili panjang dan 0 tidak.
Merupakan Type data biner.

Apakah orang ini memiliki bibir yang tipis atau tidak : 1 mewakili kurus dan 0 tidak.

Apakah jarak dari hidung ke bibir panjang : 1 mewakili ya dan 0 tidak.

Menunjukkan apakah orang tersebut berambut panjang atau tidak : 1 adalah "rambut panjang" dan 0 adalah "rambut tidak panjang".


**Isi data csv :**

gender

forehead_width_cm

forehead_height_cm

nose_wide

nose_long

lips_thin

distance_nose_to_lip_long

long_hair



In [218]:
import pandas as pd
import numpy as np
genderv7 = pd.read_csv('https://raw.githubusercontent.com/Iqbalsuryaa/pendata/main/gender_classification_v7_oke.csv')
genderv7

gender  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0       Male               11.8                 6.1          1          0   
1     Female               14.0                 5.4          0          0   
2       Male               11.8                 6.3          1          1   
3       Male               14.4                 6.1          0          1   
4     Female               13.5                 5.9          0          0   
...      ...                ...                 ...        ...        ...   
4996  Female               13.6                 5.1          0          0   
4997  Female               11.9                 5.4          0          0   
4998  Female               12.9                 5.7          0          0   
4999  Female               13.2                 6.2          0          0   
5000    Male               15.4                 5.4          1          1   

      lips_thin  distance_nose_to_lip_long  long_hair  
0             1                          1          1  
1             1                          0          0  
2             1                          1          0  
3             1                          1          0  
4             0                          0          1  
...         ...                        ...        ...  
4996          0                          0          1  
4997          0                          0          1  
4998          0                          0          1  
4999          0                          0          1  
5000          1                          1          1  

[5001 rows x 8 columns]

In [219]:
# Show all columns from dataframe
genderv7.columns

Index(['gender', 'forehead_width_cm', 'forehead_height_cm', 'nose_wide',
       'nose_long', 'lips_thin', 'distance_nose_to_lip_long', 'long_hair'],
      dtype='object')

Merubah Gender menjadi Numerik

Change Values to 1/0 Take all values of ‘gender’

If values is Female change to 1

If values is Male to 0

In [220]:
# gender code
Gen_wanita = "Female"
Gen_pria = "Male"

# binary value
value_one = 1
value_zero = 0

def change_gender_to_binary(gender):
    return value_one if gender == Gen_pria else value_zero

Meng-update hasil perubahah

In [221]:
# Update all values
genderv7["gender"] = genderv7["gender"].apply(change_gender_to_binary)

In [222]:
genderv7[['gender']].head(10)

gender
0       1
1       0
2       1
3       1
4       0
5       1
6       1
7       0
8       0
9       0

## **>> Pengujian Naive Bayes**

In [223]:
genderv7 =genderv7
X = genderv7.iloc[:,:6].values
y = genderv7['long_hair'].values
genderv7.head(5)

gender  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0       1               11.8                 6.1          1          0   
1       0               14.0                 5.4          0          0   
2       1               11.8                 6.3          1          1   
3       1               14.4                 6.1          0          1   
4       0               13.5                 5.9          0          0   

   lips_thin  distance_nose_to_lip_long  long_hair  
0          1                          1          1  
1          1                          0          0  
2          1                          1          0  
3          1                          1          0  
4          0                          0          1

In [224]:
from sklearn.preprocessing import StandardScaler
X_std=StandardScaler().fit_transform(X)
X_std

array([[ 1.00019998, -1.24793291,  0.28397148,  1.01227287, -1.01592361,
         1.01389375],
       [-0.99980006,  0.73938869, -1.00941773, -0.98787593, -1.01592361,
         1.01389375],
       [ 1.00019998, -1.24793291,  0.65351125,  1.01227287,  0.98432598,
         1.01389375],
       ...,
       [-0.99980006, -0.25427211, -0.45510807, -0.98787593, -1.01592361,
        -0.98629664],
       [-0.99980006,  0.01672629,  0.46874136, -0.98787593, -1.01592361,
        -0.98629664],
       [ 1.00019998,  2.00404789, -1.00941773,  1.01227287,  0.98432598,
         1.01389375]])

In [225]:
df_std = pd.DataFrame(X_std, columns=genderv7.columns[:6])
df_std.to_csv('preprocessed_data.csv', index=False)

In [226]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.05, random_state=42)

In [227]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [228]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [229]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1])

In [230]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))
cm

Accuracy :  0.8884462151394422


array([[  0,  28],
       [  0, 223]])

In [231]:
# Mendefinisikan fungsi untuk memprediksi RiskLevel dari input pengguna
def predict_risk_level(input_data):
    # Lakukan preprocessing pada input data
    input_data = sc.transform([input_data])  # Lakukan penskalaan pada input data

    # Lakukan prediksi menggunakan model Gaussian Naive Bayes
    predicted_risk_level = classifier.predict(input_data)

    return predicted_risk_level

In [232]:
# Contoh penggunaan fungsi predict_risk_level dengan input pengguna
input_user = [15,120,80,7.01,98,70]
predicted_risk = predict_risk_level(input_user)
print("Predicted Risk Level:", predicted_risk)

Predicted Risk Level: [1]


## **>> Pengujian K - Nearest Neighbour**

In [233]:
# Show all columns from dataframe
genderv7.columns

Index(['gender', 'forehead_width_cm', 'forehead_height_cm', 'nose_wide',
       'nose_long', 'lips_thin', 'distance_nose_to_lip_long', 'long_hair'],
      dtype='object')

In [234]:
genderv7 = genderv7
X = genderv7.iloc[:,:6].values
y = genderv7['long_hair'].values
genderv7.head(5)

gender  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0       1               11.8                 6.1          1          0   
1       0               14.0                 5.4          0          0   
2       1               11.8                 6.3          1          1   
3       1               14.4                 6.1          0          1   
4       0               13.5                 5.9          0          0   

   lips_thin  distance_nose_to_lip_long  long_hair  
0          1                          1          1  
1          1                          0          0  
2          1                          1          0  
3          1                          1          0  
4          0                          0          1

In [235]:
from sklearn.preprocessing import StandardScaler
X_std=StandardScaler().fit_transform(X)

In [236]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state=42)

In [237]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [238]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors=5)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [239]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,

In [240]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
from sklearn.metrics import accuracy_score
print ("Accuracy : ", accuracy_score(y_test, y_pred))
cm

Accuracy :  0.8522954091816367


array([[  1,  63],
       [ 11, 426]])

## **>> Pengujian Decision Tree**

In [241]:
# Show all columns from dataframe
genderv7.columns

Index(['gender', 'forehead_width_cm', 'forehead_height_cm', 'nose_wide',
       'nose_long', 'lips_thin', 'distance_nose_to_lip_long', 'long_hair'],
      dtype='object')

In [242]:
genderv7 = genderv7
X = genderv7.iloc[:,:6].values
y = genderv7['long_hair'].values
genderv7.head(5)

gender  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0       1               11.8                 6.1          1          0   
1       0               14.0                 5.4          0          0   
2       1               11.8                 6.3          1          1   
3       1               14.4                 6.1          0          1   
4       0               13.5                 5.9          0          0   

   lips_thin  distance_nose_to_lip_long  long_hair  
0          1                          1          1  
1          1                          0          0  
2          1                          1          0  
3          1                          1          0  
4          0                          0          1

In [243]:
X = genderv7.drop(['long_hair'], axis=1)
y = genderv7['long_hair']

In [244]:
from sklearn.preprocessing import StandardScaler
X_std=StandardScaler().fit_transform(X)

In [245]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 42)

In [246]:
!pip install category_encoders
import category_encoders as ce

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [247]:
from sklearn.tree import DecisionTreeClassifier

In [248]:
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=21)
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=3, random_state=21)

In [249]:
y_pred_gini = clf_gini.predict(X_test)

In [250]:
from sklearn.metrics import accuracy_score
print('Model accuracy score with criterion gini index: {0:0.2f}'. format(accuracy_score(y_test, y_pred_gini)))

Model accuracy score with criterion gini index: 0.87


In [251]:
y_pred_train_gini = clf_gini.predict(X_train)
y_pred_train_gini

array([1, 1, 1, ..., 1, 1, 1])

In [252]:
print('Training-set accuracy score: {0:0.2f}'. format(accuracy_score(y_train, y_pred_train_gini)))

Training-set accuracy score: 0.87


In [253]:
print('Training set score: {:.2f}'.format(clf_gini.score(X_train, y_train)))
print('Test set score: {:.2f}'.format(clf_gini.score(X_test, y_test)))

Training set score: 0.87
Test set score: 0.87


## **>> Pengujian Multi Layer Perceptron (MLP)**


In [254]:
# Show all columns from dataframe
genderv7.columns

Index(['gender', 'forehead_width_cm', 'forehead_height_cm', 'nose_wide',
       'nose_long', 'lips_thin', 'distance_nose_to_lip_long', 'long_hair'],
      dtype='object')

In [255]:
genderv7 = genderv7
X = genderv7.iloc[:,:6].values
y = genderv7['long_hair'].values
genderv7.head(5)

gender  forehead_width_cm  forehead_height_cm  nose_wide  nose_long  \
0       1               11.8                 6.1          1          0   
1       0               14.0                 5.4          0          0   
2       1               11.8                 6.3          1          1   
3       1               14.4                 6.1          0          1   
4       0               13.5                 5.9          0          0   

   lips_thin  distance_nose_to_lip_long  long_hair  
0          1                          1          1  
1          1                          0          0  
2          1                          1          0  
3          1                          1          0  
4          0                          0          1

In [256]:
from sklearn.preprocessing import StandardScaler
X_std=StandardScaler().fit_transform(X)

In [257]:
X = genderv7.drop(['long_hair'], axis=1)
y = genderv7['long_hair']

In [258]:
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [259]:
# Memisahkan fitur dan target
X = genderv7.drop('long_hair', axis=1)
y = genderv7['long_hair']

In [260]:
# Standarisasi fitur
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

In [261]:
# Memisahkan data menjadi data latih dan data uji
X_train, X_test, y_train, y_test = train_test_split(X_std, y, test_size=0.1, random_state=42)

In [262]:
# Membuat objek MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(100,100,100), max_iter=1000, alpha=0.0001,
                     solver='sgd', verbose=10,  random_state=21,tol=0.001)

In [263]:
# Melatih model dengan data latih
mlp.fit(X_train, y_train)

Iteration 1, loss = 0.67065133
Iteration 2, loss = 0.52291480
Iteration 3, loss = 0.44343114
Iteration 4, loss = 0.40949449
Iteration 5, loss = 0.39673438
Iteration 6, loss = 0.39166571
Iteration 7, loss = 0.38974545
Iteration 8, loss = 0.38885723
Iteration 9, loss = 0.38846253
Iteration 10, loss = 0.38831772
Iteration 11, loss = 0.38809430
Iteration 12, loss = 0.38796364
Iteration 13, loss = 0.38787760
Iteration 14, loss = 0.38778922
Iteration 15, loss = 0.38768224
Iteration 16, loss = 0.38759653
Iteration 17, loss = 0.38752534
Iteration 18, loss = 0.38745348
Training loss did not improve more than tol=0.001000 for 10 consecutive epochs. Stopping.


MLPClassifier(hidden_layer_sizes=(100, 100, 100), max_iter=1000,
              random_state=21, solver='sgd', tol=0.001, verbose=10)

In [264]:
# Memprediksi kelas dari data uji
y_pred = mlp.predict(X_test)

In [265]:
# Menghitung akurasi
accuracy = accuracy_score(y_test, y_pred)
print("Akurasi:", accuracy)

Akurasi: 0.872255489021956
